# Thông tin định danh dự án trên SonarCloud
sonar.projectKey=L01-12345_snapify-backend
sonar.organization=l01-12345

# Điểm đến của Server SonarCloud
sonar.host.url=https://sonarcloud.io

# Đường dẫn đến thư mục chứa source code chính
sonar.sources=src

# Đường dẫn đến thư mục chứa code test
sonar.tests=test

# Đường dẫn đến file Coverage do Jest sinh ra (Cực kỳ quan trọng)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Bỏ qua không quét các thư mục rác hoặc không cần thiết
sonar.exclusions=node_modules/**, coverage/**, **/*.test.js, src/config/**